name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up Elixir
      - name: Set up Elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: '1.17.3' # Define the elixir version [required]
          otp-version: '27' # Define the OTP version [required]

      # 3. Install Dependencies, Run Linter, and Run Tests
      - name: Install Dependencies, Run Linter and Tests
        run: |
          mix deps.get
          mix compile
          mix credo
          mix test