name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Код Репозитория
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Установка Elixir и Настройка Зависимостей
      - name: Install Elixir and Setup Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg2

          # Добавление репозитория Erlang Solutions для установки Erlang/OTP и Elixir
          wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb
          sudo dpkg -i erlang-solutions_2.0_all.deb
          sudo apt-get update

          # Установка Erlang/OTP и Elixir
          sudo apt-get install -y esl-erlang elixir

          # Установка Hex и Rebar (необходимы для работы mix)
          mix local.hex --force
          mix local.rebar --force

          # Получение зависимостей и компиляция проекта
          mix deps.get
          mix compile

      # 3. Запуск Линтера и Тестов
      - name: Run Linter and Tests
        run: |
          # Запуск Credo для линтинга с строгими правилами
          mix credo --strict

          # Запуск тестов проекта
          mix test